name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "deploying" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
            if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
        - name: rsync over ssh
          run: rsync ./build/ flawfyix@flawlesslogic.net:21098:Pages/timer.flawlesslogic.net/

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
        # run: |
          # echo Add other actions to build,
          # echo test, and deploy your project.
